=== SimonDanisch/Romeo.jl/src/XMLScreens/subscreenSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
            elementFormDefault="qualified" >

  <xs:annotation>
    <xs:documentation xml:lang="en">
      Part of extensions for Romeo.jl
    </xs:documentation>
  </xs:annotation>


  <!-- Comma separated lists of numbers -->
  <xs:simpleType name="listofIntsType">
     <xs:restriction base="xs:string">
        <xs:pattern value="(\d,)*\d"/>
     </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="listofFLoatsType">
     <xs:restriction base="xs:string">
        <xs:pattern value="(\d(.\d,)?)*\d(.\d)?"/>
     </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="listofFLoatExprType">
      <!--here we admit a list of Julia expressions , may be the pattern is
          too permissive ?? -->
     <xs:restriction base="xs:string">
        <xs:pattern value=".*"/>
     </xs:restriction>
  </xs:simpleType>


  <xs:element name="scene" type="sceneType"/>
  <xs:complexType name="sceneType">
   <xs:sequence>
    <xs:element name="julia" type="juliaType" 
		maxOccurs="unbounded"    minOccurs="0" />
    <xs:sequence>
       <xs:element name="subscreen"  type="subscreenType"
                   maxOccurs="unbounded" />
    </xs:sequence>
    <xs:sequence>
       <xs:element name="setplot" type="setplotType"
                   maxOccurs="unbounded" />
    </xs:sequence>
    <xs:sequence>
      <xs:element name="connection" type="connectionType"
                  maxOccurs="unbounded"  minOccurs="0"/>
    </xs:sequence>
    <xs:sequence>
     <xs:element name="debug" type="debugType"/>
    </xs:sequence>
   </xs:sequence>
  </xs:complexType>


  <!-- Part of syntax used to designate julia functions used and link to 
       containing  module(s)
   -->
  <xs:complexType name="importType">
    <xs:attribute name="fn" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="signalType">
    <xs:attribute name="name"     type="xs:string"/>
    <xs:attribute name="init"     type="xs:string"/>
    <xs:attribute name="advance"  type="xs:string"/>
    <xs:attribute name="type"     type="xs:string"/>
  </xs:complexType>


  <xs:complexType name="juliaType">
    <xs:sequence >
      <xs:choice maxOccurs="unbounded">
         <xs:element name="import" type="importType" />
         <xs:element name="inline"/>   
                  <!-- Please note that processing instruction are
                       simply ignored by XSD 1.0 and 1.1.

		       "Searching the spec for "processing instruction" gives one 
			hit, which is the sentence in 3.1.4 that says "The above definition 
			means that comments and processing instructions, even in the midst of
                        text, are ignored for all ·validation· purposes."

                       We test what is accessible at the LightXML processor level.
                  -->
         <xs:element name="signal" type="signalType" />
                  <!-- signal is used to enable RenderObjects which are 
                       dependent on signals (for instance a time dependent 
                       object)   -->
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="modulename" type="xs:string"/>
  </xs:complexType>
  <!-- End of section related to julia function and module(s)-->


  <xs:complexType name="subscreenType">
    <xs:sequence >
      <xs:element name="rowsizes" type="listofFLoatsType" 
                  maxOccurs="1"    minOccurs="0" />
      <xs:element name="colsizes" type="listofFLoatsType"
                  maxOccurs="1"    minOccurs="0" />
      <xs:element name="table" type="TableType"
                  maxOccurs="1"    minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="rows" type="xs:integer"/>
    <xs:attribute name="cols" type="xs:integer"/>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:element name="table" type="TableType"/>
  <xs:complexType name="TableType">  
    <xs:sequence>
          <xs:element name="tr"  type="TableRowType"
                      maxOccurs="unbounded"  />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TableRowType">  
    <xs:sequence>
           <xs:element name="subscreen" type="subscreenType"
                       maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="addParmType">  
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="setplotType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
         <xs:element name="rotateModel" type="listofFLoatExprType"
                  minOccurs="0" />
         <xs:element name="addparm" type="addParmType"
                  minOccurs="0" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="ref" type="xs:string"/>
    <xs:attribute name="fn" type="xs:string"/>
  </xs:complexType>


  <xs:simpleType name="listofSignals">
      <!--here we admit a list of Symbols (in Julia syntax ":xxxxx"
          this pattern is too permissive ?? -->
     <xs:restriction base="xs:string">
        <xs:pattern value="[\s\S]*"/>
     </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="connectionType">
    <xs:sequence>
      <xs:element name="inSig" type="listofSignals"/>
      <xs:element name="outSig" type="listofSignals"/>
    </xs:sequence>
    <xs:attribute name="from" type="xs:string"/>
    <xs:attribute name="to"   type="xs:string"/>
  </xs:complexType>



  <!-- instruct to print a dump of a subscreen at the end of XML 
       semantics processing 
   -->
  <xs:element name="dump" type="dumpType"/>
  <xs:complexType name="dumpType">
    <xs:attribute name="ref" type="xs:string"/>
  </xs:complexType>

  <!--Perform a set of debug actions -->
  <xs:complexType name="debugType">
    <xs:sequence>
      <xs:element name="dump" type="dumpType" 
                  minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== SimonDanisch/Romeo.jl/test/subscreenSpec4.xml
<?xml version="1.0" encoding="UTF-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:noNamespaceSchemaLocation="subscreenSchema.xsd">

<!-- Test purposes
     1) explore GLVisualize examples, here test_mesh.jl
-->
<!-- Function definitions  -->


<julia  modulename="SubScreensInline">
   <inline>
   <?julia      
      module SubScreensInline

      using GLAbstraction, GLWindow, ModernGL, GLVisualize,  AbstractGPUArray
      using ColorTypes, GeometryTypes
      using Meshes, MeshIO
      using Romeo, TBCompletedM

      export doMesh, doAxis, doMeshAxis
      
      warn ("GLAbstraction.Camera is not exported")
      Camera = GLAbstraction.Camera

      ## Example from GLVisualize/test/test_mesh
      function create_example_mesh()
          # volume of interest
          x_min, x_max = -1, 15
          y_min, y_max = -1, 5
          z_min, z_max = -1, 5
          scale = 8
       
          b1(x,y,z) = box(   x,y,z, 0,0,0,3,3,3)
          s1(x,y,z) = sphere(x,y,z, 3,3,3,sqrt(3))
          f1(x,y,z) = min(b1(x,y,z), s1(x,y,z))  # UNION
          b2(x,y,z) = box(   x,y,z, 5,0,0,8,3,3)
          s2(x,y,z) = sphere(x,y,z, 8,3,3,sqrt(3))
          f2(x,y,z) = max(b2(x,y,z), -s2(x,y,z)) # NOT
          b3(x,y,z) = box(   x,y,z, 10,0,0,13,3,3)
          s3(x,y,z) = sphere(x,y,z, 13,3,3,sqrt(3))
          f3(x,y,z) = max(b3(x,y,z), s3(x,y,z))  # INTERSECTION
          f(x,y,z) = min(f1(x,y,z), f2(x,y,z), f3(x,y,z))
       
          vol = volume(f, x_min,y_min,z_min,x_max,y_max,z_max, scale)
          msh = GLNormalMesh(vol, 0.0f0)
          return msh
      end

      function create_example_axis()
        dirlen 	= 1f0
        baselen = 0.02f0
        axis 	= [
      	 (Cube(Vec3(baselen), Vec3(dirlen, baselen, baselen)), RGBA(1f0,0f0,0f0,1f0)), 
      	 (Cube(Vec3(baselen), Vec3(baselen, dirlen, baselen)), RGBA(0f0,1f0,0f0,1f0)), 
      	 (Cube(Vec3(baselen), Vec3(baselen, baselen, dirlen)), RGBA(0f0,0f0,1f0,1f0))
          ]
        axis = map(GLNormalMesh, axis)
        axis = merge(axis)
      end

      function doMesh(sc::Screen,cam::Camera)
          println("Entered doMesh")
	  msh  = create_example_mesh()
          msh
      end

     function doAxis (sc::Screen,cam::Camera)
          println("Entered doAxis")
          ax   = create_example_axis()
          ax
     end

     function doMeshAxis (sc::Screen,cam::Camera)
          println("Entered doMeshAxis")
	  msh  = create_example_mesh()
          ax   = create_example_axis()
          (msh,ax)
     end

      end    # SubScreensInline
   ?>
   </inline>
</julia>
<!-- Subscreen description -->
 <subscreen rows="2" cols="2" name="MAIN">
  <rowsizes>1,4</rowsizes>
  <colsizes>4,1</colsizes>
  <table>
    <tr>
     <subscreen name="A1"/>
     <subscreen name="A2"/>
     </tr>
    <tr>
     <subscreen name="B1"/>
     <subscreen name="INNER"/>
     </tr>
   </table>
 </subscreen>

 <subscreen rows="4" cols="1" name="INNER">
  <rowsizes>1,1,1,1</rowsizes>
  <colsizes>1</colsizes>
  <table>
    <tr>
     <subscreen name="IA1"/>
    </tr>
    <tr>
     <subscreen name="IB1"/>
    </tr>
    <tr>
     <subscreen name="IC1"/>
    </tr>
    <tr>
     <subscreen name="ID1"/>
    </tr>
   </table>
 </subscreen>

<!-- Subscreen contents -->

 <setplot  ref="A1"  fn="doMesh"/>
 <setplot  ref="A2"  fn="doAxis"/>
 <setplot  ref="B1"  fn="doMesh"/>

 <setplot  ref="IA1"  fn="doMesh"/>
 <setplot  ref="IB1"  fn="doMesh"> 
      <rotateModel>Pi/2, 0.0, 0.0</rotateModel>
 </setplot>
 <setplot  ref="IC1"  fn="doMesh">
      <rotateModel>0.0, Pi/2, 0.0</rotateModel>
 </setplot>
 <setplot  ref="ID1"  fn="doMesh">
      <rotateModel>0.0, 0.0, Pi/2</rotateModel>
 </setplot>

 <!-- Connectors -->
 <connection from="B1" to="A2"> 
            <inSig>:view  </inSig> <!-- , :projection,    :projectionview, :projection-->
            <outSig>:view </outSig> <!-- , :projectionview,:projection,    :projection-->
 </connection>

 <!-- Debug options -->

<debug>
    <dump ref="IC1"/>
</debug>

</scene>
<!-- This ends the scene-->
