=== SimonDanisch/Romeo.jl/src/XMLScreens/subscreenSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
            elementFormDefault="qualified" >

  <xs:annotation>
    <xs:documentation xml:lang="en">
      Part of extensions for Romeo.jl
    </xs:documentation>
  </xs:annotation>


  <!-- Comma separated lists of numbers -->
  <xs:simpleType name="listofIntsType">
     <xs:restriction base="xs:string">
        <xs:pattern value="(\d,)*\d"/>
     </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="listofFLoatsType">
     <xs:restriction base="xs:string">
        <xs:pattern value="(\d(.\d,)?)*\d(.\d)?"/>
     </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="listofFLoatExprType">
      <!--here we admit a list of Julia expressions , may be the pattern is
          too permissive ?? -->
     <xs:restriction base="xs:string">
        <xs:pattern value=".*"/>
     </xs:restriction>
  </xs:simpleType>


  <xs:element name="scene" type="sceneType"/>
  <xs:complexType name="sceneType">
   <xs:sequence>
    <xs:element name="julia" type="juliaType" 
		maxOccurs="unbounded"    minOccurs="0" />
    <xs:sequence>
       <xs:element name="subscreen"  type="subscreenType"
                   maxOccurs="unbounded" />
    </xs:sequence>
    <xs:sequence>
       <xs:element name="setplot" type="setplotType"
                   maxOccurs="unbounded" />
    </xs:sequence>
    <xs:sequence>
      <xs:element name="connection" type="connectionType"
                  maxOccurs="unbounded"  minOccurs="0"/>
    </xs:sequence>
    <xs:sequence>
     <xs:element name="debug" type="debugType"/>
    </xs:sequence>
   </xs:sequence>
  </xs:complexType>


  <!-- Part of syntax used to designate julia functions used and link to 
       containing  module(s)
   -->
  <xs:complexType name="importType">
    <xs:attribute name="fn" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="signalType">
    <xs:attribute name="name"     type="xs:string"/>
    <xs:attribute name="init"     type="xs:string"/>
    <xs:attribute name="advance"  type="xs:string"/>
    <xs:attribute name="type"     type="xs:string"/>
  </xs:complexType>


  <xs:complexType name="juliaType">
    <xs:sequence >
      <xs:choice maxOccurs="unbounded">
         <xs:element name="import" type="importType" />
         <xs:element name="inline"/>   
                  <!-- Please note that processing instruction are
                       simply ignored by XSD 1.0 and 1.1.

		       "Searching the spec for "processing instruction" gives one 
			hit, which is the sentence in 3.1.4 that says "The above definition 
			means that comments and processing instructions, even in the midst of
                        text, are ignored for all ·validation· purposes."

                       We test what is accessible at the LightXML processor level.
                  -->
         <xs:element name="signal" type="signalType" />
                  <!-- signal is used to enable RenderObjects which are 
                       dependent on signals (for instance a time dependent 
                       object)   -->
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="modulename" type="xs:string"/>
  </xs:complexType>
  <!-- End of section related to julia function and module(s)-->


  <xs:complexType name="subscreenType">
    <xs:sequence >
      <xs:element name="rowsizes" type="listofFLoatsType" 
                  maxOccurs="1"    minOccurs="0" />
      <xs:element name="colsizes" type="listofFLoatsType"
                  maxOccurs="1"    minOccurs="0" />
      <xs:element name="table" type="TableType"
                  maxOccurs="1"    minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="rows" type="xs:integer"/>
    <xs:attribute name="cols" type="xs:integer"/>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:element name="table" type="TableType"/>
  <xs:complexType name="TableType">  
    <xs:sequence>
          <xs:element name="tr"  type="TableRowType"
                      maxOccurs="unbounded"  />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TableRowType">  
    <xs:sequence>
           <xs:element name="subscreen" type="subscreenType"
                       maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="addParmType">  
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="setplotType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
         <xs:element name="rotateModel" type="listofFLoatExprType"
                  minOccurs="0" />
         <xs:element name="addparm" type="addParmType"
                  minOccurs="0" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="ref" type="xs:string"/>
    <xs:attribute name="fn" type="xs:string"/>
  </xs:complexType>


  <xs:simpleType name="listofSignals">
      <!--here we admit a list of Symbols (in Julia syntax ":xxxxx"
          this pattern is too permissive ?? -->
     <xs:restriction base="xs:string">
        <xs:pattern value="[\s\S]*"/>
     </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="connectionType">
    <xs:sequence>
      <xs:element name="inSig" type="listofSignals"/>
      <xs:element name="outSig" type="listofSignals"/>
    </xs:sequence>
    <xs:attribute name="from" type="xs:string"/>
    <xs:attribute name="to"   type="xs:string"/>
  </xs:complexType>



  <!-- instruct to print a dump of a subscreen at the end of XML 
       semantics processing 
   -->
  <xs:element name="dump" type="dumpType"/>
  <xs:complexType name="dumpType">
    <xs:attribute name="ref" type="xs:string"/>
  </xs:complexType>

  <!--Perform a set of debug actions -->
  <xs:complexType name="debugType">
    <xs:sequence>
      <xs:element name="dump" type="dumpType" 
                  minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== SimonDanisch/Romeo.jl/test/subscreenSpec6b.xml
<?xml version="1.0" encoding="UTF-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="subscreenSchema.xsd">

<!-- Test purposes
     1) use a real time timer to sequence timed display(s)
     2) show axes frames subject or not to <rotationModel>
     Note: Currently we have a number of issues for transmission of global or
           module local data. Therefore using wired in values for some dimensions.
-->
<!-- Function definitions  -->
<julia  modulename="SubScreensInline2">
   <inline>
   <?julia      
      module SubScreensInline2

      using GLAbstraction, GLWindow, ModernGL, GLVisualize,  AbstractGPUArray
      using ColorTypes, GeometryTypes
      using Meshes, MeshIO
      using Romeo, TBCompletedM

      export doAxis
      
      warn ("GLAbstraction.Camera is not exported")
      Camera = GLAbstraction.Camera

      function create_example_axis(scale::Float32)
        dirlen 	= Float32(scale)
        baselen = 0.02f0*Float32(scale)
        axis 	= [
      	 (Cube(Vec3(0.0f0), Vec3(dirlen, baselen, baselen)), RGBA(1f0,0f0,0f0,1f0)), 
      	 (Cube(Vec3(0.0f0), Vec3(baselen, dirlen, baselen)), RGBA(0f0,1f0,0f0,1f0)), 
      	 (Cube(Vec3(0.0f0), Vec3(baselen, baselen, dirlen)), RGBA(0f0,0f0,1f0,1f0))
          ]
        axis = map(GLNormalMesh, axis)
        axis = merge(axis)
      end

     function doAxis (sc::Screen,cam::Camera,scale::Float32=1.0f0)
          println("Entered doAxis")
          ax   = create_example_axis(scale)
          ax1  = visualize(ax,camera=cam, screen=sc)
          (ax,ax1)
     end
      end    # SubScreensInline2
   ?>
   </inline>
</julia>



<julia  modulename="SubScreensInline">
   <signal name="timer"
           init="timerInitFun"
           type="Reactive.Input{Int64}"/>
   <!-- now  read the inlined Julia code -->
   <inline>
   <?julia
module SubScreensInline

using GLAbstraction, GLWindow, ModernGL, GLVisualize,  AbstractGPUArray
using ColorTypes, GeometryTypes
using Meshes, MeshIO
using Reactive
using Romeo, TBCompletedM
using ODE

using xmlNS.SubScreensInline2

export doPlanets,  doPlanetSpeeds, timerInitFun, timerAdvanceFun

warn ("GLAbstraction.Camera is not exported")
Camera = GLAbstraction.Camera

particleColors = Array{Any,1}(0)

      ## Example from GLVisualize/test/nbody.jl
@inbounds function F(t::Float64,y::Array{Float64,1})
    
    #Number of Planets (note we're solving the n-body problem, rather than just a 3-body problem)
    n::Int = int(length(y)/6)

    #Extract current position and velocity
    r::Array{Float64,2} = zeros(Float64,n,3)
    v::Array{Float64,2} = zeros(Float64,n,3)
     @simd for i=1:n
         r[i,:] = y[(i-1)*6+1:(i-1)*6+3]
         v[i,:] = y[(i-1)*6+4:(i-1)*6+6]
    end

    #Calculate spatial derivatives
    drdt :: Array{Float64,2} = v

    #Work out velocity derivatives (ie accelerations)
    dvdt::Array{Float64,2} = zeros(Float64,n,3)
    for i = 1:n
        for j = 1:n
            if i != j
             dvdt[i,:] += -G * m[j] * (r[i,:]-r[j,:]) / ( norm(r[i,:]-r[j,:])^3 )
            end
        end
    end

    #Combine back together into dydt vector
    dydt::Array{Float64,1} = zeros(Float64,6*n)
     @simd for i = 1:n
         dydt[6(i-1)+1] = drdt[i,1]
         dydt[6(i-1)+2] = drdt[i,2]
         dydt[6(i-1)+3] = drdt[i,3]
         dydt[6(i-1)+4] = dvdt[i,1]
         dydt[6(i-1)+5] = dvdt[i,2]
         dydt[6(i-1)+6] = dvdt[i,3]
    end
    return dydt
end  # Function F(t,y)

function worldCreate()

   #Set the masses
   global m
   m = [5,4,3,5]
   n = length(m)

   #Set the gravitational field strength
   global G
   G = .2

   #Set initial positions and velocities
   r0 = zeros(n,3)
   r0[1,:] = [ 1.0, -1.0,  1.0]
   r0[2,:] = [ 1.0,  0.0,  0.0]
   r0[3,:] = [ 0.0,  0.0, -1.0]
   r0[4,:] = [ 0.0,  0.0,  0.0]

   #Select a reasonable set of speeds (avoid cases where
   #       a singularity happens stopping the ode solver. Arrange for
   #       a null momentum so that the world stays on the screen. )
   v0 = rand(n,3)
   mv = m' * v0 / sum(m)
   v0 = v0 - ones(4,1) * mv


   # Aggregate initial data (position, speed)  in a format that
   # the ODE solver and function F handle
   y0 = zeros(6*n)
   for i = 1:n
     y0[6(i-1)+1] = r0[i,1]
     y0[6(i-1)+2] = r0[i,2]
     y0[6(i-1)+3] = r0[i,3]
     y0[6(i-1)+4] = v0[i,1]
     y0[6(i-1)+5] = v0[i,2]
     y0[6(i-1)+6] = v0[i,3]
   end
    return (m,y0,G)
end

function worldOperate(y0)
   #Solve the system
   tf = 10
   stepsPerUnitTime = 200
   tspan = linspace(0,tf,tf*stepsPerUnitTime)
   t,y = ode23s(F, y0, tspan; points=:specified);
   return t,y
end

function worldStore()
    global world
    if !isdefined(:world)
        m,y0,G = worldCreate()
        t,y    = worldOperate(y0)
        planets      = reformatData(m, t, y)
        planetspeeds = reformatSpeeds(m, t, y)
        len= size(planets, 1)
        world = WorldType(m, length(m), y0, G, t, y, planets, planetspeeds, len)
    end
end

function mkParticleColors(n::Int)
    global particleColors
    if length(particleColors) == 0
          particleColors = Array{Any,1}(n)
          for i in 1:n
             particleColors[i] =  RGBA(rand(Float32,3)..., 0.4f0)
          end
    end
end

function send_frame(i, planets)
    p = planets[i, 1:4]
    reshape(p, (2,2))
end

function reformatData(m, t, y)
    #Extract the data into a useful form
    n = length(m)
    ymat= hcat(y...)

    # gather some results, do we need to construct such an array
    # positions
    rcoords = sort([  [6(i-1)+1 for i = 1:n],
                      [6(i-1)+2 for i = 1:n],
                      [6(i-1)+3 for i = 1:n]])
    rcoords = convert(Array{Int64,1}, rcoords)
    const r = map(Float32, ymat[rcoords,:])

    const planets = hcat( [ reinterpret(Point3{Float32},
                                        r[3(i-1)+1:3(i-1)+3,:],
                                        (size(r, 2),)) for i=1:n]...)
    println("size(planets[:, 1]=", size(planets[:, 1]))
    return planets
end


function reformatSpeeds(m, t, y)
    #Extract the data into a useful form
    n = length(m)
    ymat= hcat(y...)

    # gather some results, do we need to construct such an array
    # positions
    rcoords = sort([  [6(i-1)+4 for i = 1:n],
                      [6(i-1)+5 for i = 1:n],
                      [6(i-1)+6 for i = 1:n]])
    rcoords = convert(Array{Int64,1}, rcoords)
    const r = map(Float32, ymat[rcoords,:])

    const speeds = hcat( [ reinterpret(Point3{Float32},
                                        r[3(i-1)+1:3(i-1)+3,:],
                                        (size(r, 2),)) for i=1:n]...)
    return speeds
end


type WorldType
     masses
     nb
     yInit
     G
     tsteps
     YV
     planets
     speeds
     lenPlanets
end



function doPlanets( sc::Screen,cam::Camera, time_i) # beware 3rd result
    global world
    worldStore()

    global particleColors
    mkParticleColors(world.nb)

    # this is used for communication with timerAdvanceFun
    lenPlanet =  world.lenPlanets

    const positions     = lift(send_frame, time_i, Input(world.planets))
    const robj          = visualize(positions, model=scalematrix(Vec3(0.1f0)),
                                    screen=sc, camera=cam)


    const robjPl  = [ visualize(reshape(world.planets[:, i], (round(Int,lenPlanet/20), 20)),
				particle_color= particleColors[i],
    				model=scalematrix(Vec3(0.01f0)),
                                screen=sc, camera=cam)
                       for i=1:4]

    # this conversion is required, otherwise loss of type information
    robjPlTy = Array{RenderObject,1}(robjPl)

    return (robj, robjPlTy, doAxis(sc,cam,3.0f0))
end

function doPlanetSpeeds( sc::Screen,cam::Camera, time_i) # beware 3rd result
    global world
    worldStore()
    global particleColors
    mkParticleColors(world.nb)

    # this is used for communication with timerAdvanceFun
    lenPlanet =  world.lenPlanets

    speedScale= 3.0
    @show typeof(world.speeds)
    const posSpeeds   = lift(send_frame, time_i, Input(world.speeds))
    const robjSpeed   = visualize(posSpeeds, model=scalematrix(Vec3(0.3f0)),
                                  screen=sc, camera=cam)


    const robjPl  = [ visualize( reshape( world.speeds[:, i] , 
                                         (round(Int,lenPlanet/20), 20)),
		particle_color= particleColors[i],
    		model=scalematrix(Vec3(0.03f0)), 
                screen=sc, camera=cam)
                for i=1:4]

    # this conversion is required, otherwise loss of type information
    robjPlTy = Array{RenderObject,1}(robjPl)

    return (robjSpeed, robjPlTy, doAxis(sc,cam,3.0f0))
end



#  provide the timing signal:
function timerInitFun()
   lenPlanets = 1950    # wired in for now  (need to understand the context )
   freq = 0.02  # 1/50  of a second
   println("In timerInitFun")
   realClk = every(freq)
   # define a reduction ending in increment (modulo m)
   moduloAlt = s -> foldl( (x,y) ->  (x+1)%lenPlanets, 0, s)   
   return moduloAlt(realClk)
end


end    # SubScreensInline

   ?>
   </inline>
</julia>
<!-- Subscreen description -->
 <subscreen rows="2" cols="1" name="MAIN">
  <rowsizes>1,4</rowsizes>
  <colsizes>1</colsizes>
  <table>
    <tr>
     <subscreen name="A1"/>
     </tr>
    <tr>
     <subscreen name="INNER"/>
     </tr>
   </table>
 </subscreen>

 <subscreen rows="1" cols="2" name="INNER">
  <rowsizes>1</rowsizes>
  <colsizes>1,1</colsizes>
  <table>
    <tr>
     <subscreen name="IA1"/>
     <subscreen name="IB1"/>
    </tr>
   </table>
 </subscreen>

<!-- Subscreen contents -->

 <setplot  ref="IA1"  fn="doPlanets">
       <addparm name="timer" />
       <rotateModel>Pi/5, 0.0, 4*Pi/6</rotateModel>
 </setplot>

 <setplot  ref="IB1"  fn="doPlanetSpeeds">
       <addparm name="timer" />
       <rotateModel>Pi/5, 0.0, 4*Pi/6</rotateModel>
 </setplot>

 <!-- Connectors -->

 <!-- Debug options -->

<debug>
</debug>

</scene>
<!-- This ends the scene-->

=== SimonDanisch/Romeo.jl/test/subscreenSpec.xml
<?xml version="1.0" encoding="UTF-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:noNamespaceSchemaLocation="subscreenSchema.xsd">

<!-- Test purposes
      1) build screen tree hierarchy from 2 subtrees related symbolically
         (id INNER)
      2) test tag &gt;inline&lt;
      3) test symbolic reference to screen building functions defined 
         programmatically (doPlot)
      4) test connectors (TBD)
-->
<!-- Function definitions  -->

<julia  >
   <inline>
   <?julia
      begin  #list of functions
      function tyty(x,y)
           println("In tyty x=$x,y=$y")
      end
      function tyty2(x,y)
           println("In tyty2 x=$x,y=$y")
      end
      end  #list of functions
   ?>
   </inline>
</julia>

<julia  modulename="SubScreensInline">
   <inline>
   <?julia      
      module MachinChose  # test that we will be able to rename
                          # the module according to the attribute modulename
                          # For now we must start the processing instruction 
			  # with the enclosing module definition. (really a bug)
      using GLAbstraction, GLWindow, ModernGL, GLVisualize
      using Romeo, TBCompletedM
      export doPlot2D, doPlot3D

      warn ("GLAbstraction.Camera is not exported")
      Camera = GLAbstraction.Camera


      
         # try with a plot
         npts = 50 
         function plotFn2D(i,j)
               x = Float32(i)/Float32(npts)-0.5 
               y = Float32(j)/Float32(npts)-0.5 
               ret = if ( x>=0 ) && ( x>=y)
                         4*x*x+2*y*y
                     elseif ( x<0) 
                         2*sin(2.0*3.1416*x)*sin(3.0*3.1416*y)
                     else
                         0.0
                     end
                ret
         end
         function doPlot2D (sc::Screen,cam::Camera)
                 println("Entered doPlot2D")
                 ret = TBCompleted ( Float32[ plotFn2D(i,j)  for i=0:npts, j=0:npts ],
                               nothing, Dict{Symbol,Any}(:SetPerspectiveCam => true)
                             )
                 println("Exit doPlot2D returning")
                 ret
         end  
         npts3D = 12
         function plotFn3D(i,j,k)
               x = Float32(i)/Float32(npts3D)-0.5 
               y = Float32(j)/Float32(npts3D)-0.5 
               z = Float32(k)/Float32(npts3D)-0.5 

               ret = if ( x>=0 ) && ( x>=y)
                         2*x*x+3*y*y+z*z
                     elseif ( x<0) 
                         2*sin(2.0*3.1416*x)*sin(3.0*3.1416*y)
                     else
                         9*x*y*z
                     end
                ret
         end
         function doPlot3D (sc::Screen,cam::Camera)
                 println("Entered doPlot3D")
                 dd = Dict{Symbol,Any}(:SetPerspectiveCam => true) 
                 ret= TBCompleted ( Float32[ plotFn3D(i,j,k) for i=0:npts3D, 
                                         j=0:npts3D, k=0:npts3D ],
                               nothing, dd)
                 println("Exit doPlot3D returning")
                 ret
         end  
      end    #  module MachinChose
   ?>
   </inline>
</julia>
<!-- Subscreen description -->
 <subscreen rows="2" cols="2" name="MAIN">
  <rowsizes>1,4</rowsizes>
  <colsizes>4,1</colsizes>
  <table>
    <tr>
     <subscreen name="A1"/>
     <subscreen name="A2"/>
     </tr>
    <tr>
     <subscreen name="B1"/>
     <subscreen name="INNER"/>
     </tr>
   </table>
 </subscreen>

 <subscreen rows="4" cols="1" name="INNER">
  <rowsizes>1,1,1,1</rowsizes>
  <colsizes>1</colsizes>
  <table>
    <tr>
     <subscreen name="IA1"/>
    </tr>
    <tr>
     <subscreen name="IB1"/>
    </tr>
    <tr>
     <subscreen name="IC1"/>
    </tr>
    <tr>
     <subscreen name="ID1"/>
    </tr>
   </table>
 </subscreen>

<!-- Subscreen contents -->

 <setplot  ref="A1"  fn="doPlot2D"/>
 <setplot  ref="A2"  fn="doPlot3D"/>
 <setplot  ref="B1"  fn="doPlot"/>

 <setplot  ref="IA1"  fn="doColorBtn"/>
 <setplot  ref="IB1"  fn="doPlot"> 
      <rotateModel>Pi/2, 0.0, 0.0</rotateModel>
 </setplot>
 <setplot  ref="IC1"  fn="doPlot">
      <rotateModel>0.0, Pi/2, 0.0</rotateModel>
 </setplot>
 <setplot  ref="ID1"  fn="doPlot">
      <rotateModel>0.0, 0.0, Pi/2</rotateModel>
 </setplot>

 <!-- Connectors -->
 <connection from="B1" to="A2"> 
       <inSig>:view  , :adhoc,  :projection,    :projectionview, :projection
              </inSig> 
       <outSig>:view , :adhoc,  :projectionview,:projection,    :projection
              </outSig> 
 </connection>

 <!-- Debug options -->

<debug>
    <dump ref="IC1"/>
</debug>

</scene>
<!-- This ends the scene-->

=== SimonDanisch/Romeo.jl/test/subscreenSpec2.xml
<?xml version="1.0" encoding="UTF-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:noNamespaceSchemaLocation="subscreenSchema.xsd">

<!-- Test purposes
      1) build screen tree hierarchy by subscreen (recursive) insertion
      2) test tag &gt;import&lt;
      3) test symbolic reference to screen building functions defined 
         in imported julia code and mixing with programmatically defined
         stuff.       
      4) test connectors,including adhoc rules and multiple connections
-->
<!-- Function definitions  -->

<julia   modulename="SubScreensModule">
   <import fn="doPlot2D"/>
   <import fn="doPlot3D"/>
</julia>

<!-- Subscreen description -->

 <subscreen rows="2" cols="2" name="MAIN">
  <rowsizes>1,4</rowsizes>
  <colsizes>4,1</colsizes>
  <table>
    <tr>
     <subscreen name="A1"/>
     <subscreen name="A2"/>
     </tr>
    <tr>
     <subscreen name="B1"/>
     <subscreen rows="4" cols="1" name="INNER">
         <rowsizes>1,1,1,1</rowsizes>
         <colsizes>1</colsizes>
         <table>
             <tr><subscreen name="IA1"/></tr>
             <tr><subscreen name="IB1"/></tr>
             <tr><subscreen name="IC1"/></tr>
             <tr><subscreen name="ID1"/></tr>
         </table>
     </subscreen>
    </tr>
   </table>
 </subscreen>


<!-- Subscreen contents -->

 <setplot  ref="A1"  fn="doPlot2D"/>
 <setplot  ref="A2"  fn="doPlot3D"/>
 <setplot  ref="B1"  fn="doPlot2D"/>

 <setplot  ref="IA1"  fn="doPic"/>
 <setplot  ref="IB1"  fn="doPlot3D"> 
      <rotateModel>Pi/5,0.0,0.0</rotateModel>
 </setplot>
 <setplot  ref="IC1"  fn="doPlot3D">
      <rotateModel>0.0, Pi/5,0.0</rotateModel>
 </setplot>
 <setplot  ref="ID1"  fn="doPlot3D">
      <rotateModel>0.0,0.0, Pi/5</rotateModel>
 </setplot>

 <!-- Connectors -->
 <connection from="B1" to="A2"> 
      <inSig>:view  , :adhoc, :projection,    :projectionview, :projection, 
              </inSig> 
       <outSig>:view , :adhoc, :projectionview,:projection,    :projection,
              </outSig> 
 </connection>
 <connection from="B1" to="IB1"> 
      <inSig>:view  , :adhoc, :projection,    :projectionview, :projection, 
              </inSig> 
       <outSig>:view , :adhoc, :projectionview,:projection,    :projection,
              </outSig> 
 </connection>
 <connection from="B1" to="IC1"> 
      <inSig>:view  , :adhoc,  :projection,    :projectionview, :projection, 
              </inSig> 
       <outSig>:view , :adhoc, :projectionview,:projection,    :projection,
              </outSig> 
 </connection>
 <connection from="B1" to="ID1"> 
      <inSig>:view  ,  :adhoc, :projection,    :projectionview, :projection, 
              </inSig> 
       <outSig>:view , :adhoc, :projectionview,:projection,    :projection,
              </outSig> 
 </connection>

 <!-- Debug options -->

<debug>
    <dump ref="IC1"/>
</debug>

</scene>
<!-- This ends the scene-->

=== SimonDanisch/Romeo.jl/test/subscreenSpec3b.xml
<?xml version="1.0" encoding="UTF-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:noNamespaceSchemaLocation="subscreenSchema.xsd">

<!-- Test purposes
      1) explore construction of combined objects by returning Tuples
      2) better cover issues in <setplot><rotateModel>
-->
<!-- Function definitions  -->


<julia  modulename="SubScreensInline">
   <inline>
   <?julia      
      module SubScreensInline

      using GLAbstraction, GLWindow, ModernGL, GLVisualize,  AbstractGPUArray
      using ColorTypes, GeometryTypes
      using Meshes, MeshIO
      using Romeo, TBCompletedM

      export doMesh, doAxis, doMeshAxis,  doPlot2D, doMeshAxisPlot
      
      warn ("GLAbstraction.Camera is not exported")
      Camera = GLAbstraction.Camera

      ## Example from GLVisualize/test/test_mesh
      function create_example_mesh()
          # volume of interest
          x_min, x_max = -1, 15
          y_min, y_max = -1, 5
          z_min, z_max = -1, 5
          scale = 8
       
          b1(x,y,z) = box(   x,y,z, 0,0,0,3,3,3)
          s1(x,y,z) = sphere(x,y,z, 3,3,3,sqrt(3))
          f1(x,y,z) = min(b1(x,y,z), s1(x,y,z))  # UNION
          b2(x,y,z) = box(   x,y,z, 5,0,0,8,3,3)
          s2(x,y,z) = sphere(x,y,z, 8,3,3,sqrt(3))
          f2(x,y,z) = max(b2(x,y,z), -s2(x,y,z)) # NOT
          b3(x,y,z) = box(   x,y,z, 10,0,0,13,3,3)
          s3(x,y,z) = sphere(x,y,z, 13,3,3,sqrt(3))
          f3(x,y,z) = max(b3(x,y,z), s3(x,y,z))  # INTERSECTION
          f(x,y,z) = min(f1(x,y,z), f2(x,y,z), f3(x,y,z))
       
          vol = volume(f, x_min,y_min,z_min,x_max,y_max,z_max, scale)
          msh = GLNormalMesh(vol, 0.0f0)
          return msh
      end

      function create_example_axis()
        dirlen 	= 1f0
        baselen = 0.02f0
        axis 	= [
      	 (Cube(Vec3(baselen), Vec3(dirlen, baselen, baselen)), RGBA(1f0,0f0,0f0,1f0)), 
      	 (Cube(Vec3(baselen), Vec3(baselen, dirlen, baselen)), RGBA(0f0,1f0,0f0,1f0)), 
      	 (Cube(Vec3(baselen), Vec3(baselen, baselen, dirlen)), RGBA(0f0,0f0,1f0,1f0))
          ]
        axis = map(GLNormalMesh, axis)
        axis = merge(axis)
      end

      function doMesh(sc::Screen,cam::Camera)
          println("Entered doMesh")
	  msh  = create_example_mesh()
          msh
      end

     function doAxis (sc::Screen,cam::Camera)
          println("Entered doAxis")
          ax   = create_example_axis()
          ax
     end

     function doMeshAxis (sc::Screen,cam::Camera)
          println("Entered doMeshAxis")
	  msh  = create_example_mesh()
          ax   = create_example_axis()
          (msh,ax)
     end


          # try with a plot
         function plotFn2D(i,j, npts::Int)
               x = Float32(i)/Float32(npts)-0.5 
               y = Float32(j)/Float32(npts)-0.5 
               ret = if ( x>=0 ) && ( x>=y)
                         4*x*x+2*y*y
                     elseif ( x<0) 
                         2*sin(2.0*3.1416*x)*sin(3.0*3.1416*y)
                     else
                         0.0
                     end
                ret
         end
         function doPlot2D (sc::Screen,cam::Camera)
                 println("Entered doPlot2D")
                 npts=50
                 ret = TBCompleted ( Float32[ plotFn2D(i,j,npts)  for i=0:npts, j=0:npts ],
                               nothing, Dict{Symbol,Any}(:SetPerspectiveCam => true)
                             )
                 println("Exit doPlot2D returning")
                 ret
         end  

     function doMeshAxisPlot (sc::Screen,cam::Camera)
          println("Entered doMeshAxis")
	  msh  = create_example_mesh()
          ax   = create_example_axis()
          plt =  doPlot2D(sc,cam,)
          (msh,ax,plt)
     end

      end    # SubScreensInline
   ?>
   </inline>
</julia>
<!-- Subscreen description -->
 <subscreen rows="2" cols="2" name="MAIN">
  <rowsizes>1,4</rowsizes>
  <colsizes>4,1</colsizes>
  <table>
    <tr>
     <subscreen name="A1"/>
     <subscreen name="A2"/>
     </tr>
    <tr>
     <subscreen name="B1"/>
     <subscreen name="INNER"/>
     </tr>
   </table>
 </subscreen>

 <subscreen rows="4" cols="1" name="INNER">
  <rowsizes>1,1,1,1</rowsizes>
  <colsizes>1</colsizes>
  <table>
    <tr>
     <subscreen name="IA1"/>
    </tr>
    <tr>
     <subscreen name="IB1"/>
    </tr>
    <tr>
     <subscreen name="IC1"/>
    </tr>
    <tr>
     <subscreen name="ID1"/>
    </tr>
   </table>
 </subscreen>

<!-- Subscreen contents -->

 <setplot  ref="A1"  fn="doMesh"/>
 <setplot  ref="A2"  fn="doAxis"/>
 <setplot  ref="B1"  fn="doMeshAxisPlot"/>

 <setplot  ref="IA1"  fn="doMeshAxisPlot">
      <rotateModel>Pi/3, 0.0, 0.0</rotateModel>
 </setplot>
 <setplot  ref="IB1"  fn="doMeshAxisPlot"> 
      <rotateModel>0.0, Pi/3,  0.0</rotateModel>
 </setplot>
 <setplot  ref="IC1"  fn="doMeshAxisPlot">
      <rotateModel>0.0, 0.0, Pi/3</rotateModel>
 </setplot>
 <setplot  ref="ID1"  fn="doMeshAxisPlot">
      <rotateModel>2*Pi/3, 0.0, 0.0</rotateModel>
 </setplot>

 <!-- Connectors -->
 <connection from="B1" to="A2"> 
       <inSig>:view  , :viewmodel, :adhoc, :projection,    :projectionview, 
              :projection       </inSig> 
       <outSig>:view , :viewmodel, :adhoc, :projectionview,:projection,
              :projection      </outSig> 
 </connection>

 <!-- Debug options -->

<debug>
    <dump ref="IB1"/>
    <dump ref="IC1"/>
    <dump ref="ID1"/>
</debug>

</scene>
<!-- This ends the scene-->
